In [74]:
import pandas as pd

In [75]:
df = pd.read_csv('/Users/lsiddiqsunny/Documents/Notre_Dame/Research/ICSE23-results/CodeGen/SF110-Results/csv-data/JaCoCo_CodeGen_SF110.csv')
project_df = df[(df['SCENARIO'] == 'original')][['GROUP', 'PACKAGE', 'CLASS']]
project_df.drop_duplicates(inplace=True)
project_df.describe

<bound method NDFrame.describe of              GROUP             PACKAGE                                CLASS
52         saxpath  com.werken.saxpath                  DefaultXPathHandler
53         saxpath  com.werken.saxpath        DefaultXPathHandler.Singleton
54         saxpath  com.werken.saxpath                                Token
55         saxpath  com.werken.saxpath                           XPathLexer
56         saxpath  com.werken.saxpath                          XPathReader
...            ...                 ...                                  ...
21975  sbmlreader2         sbmlreader2                           SBMLFilter
21976  sbmlreader2         sbmlreader2                       AddToClasspath
21977  sbmlreader2         sbmlreader2  SBMLReaderPlugin2.SBMLReader2Action
21978  sbmlreader2         sbmlreader2               SBMLVisualStyleFactory
21979  sbmlreader2         sbmlreader2                    SBMLReaderPlugin2

[3543 rows x 3 columns]>

In [76]:
for model in ['Codex','ChatGPT-3.5','CodeGen']:
    for scenario in ["original", "scenario1", "scenario2", "scenario3", "scenario4"]:
        for token in [2000,4000]:
            if model!='Codex' and token==4000:
                continue
            print(model, scenario, token)
            project_df[model+'_'+scenario+'_'+str(token)] = [0 for i in range(len(project_df))]

Codex original 2000
Codex original 4000
Codex scenario1 2000
Codex scenario1 4000
Codex scenario2 2000
Codex scenario2 4000
Codex scenario3 2000
Codex scenario3 4000
Codex scenario4 2000
Codex scenario4 4000
ChatGPT-3.5 original 2000
ChatGPT-3.5 scenario1 2000
ChatGPT-3.5 scenario2 2000
ChatGPT-3.5 scenario3 2000
ChatGPT-3.5 scenario4 2000
CodeGen original 2000
CodeGen scenario1 2000
CodeGen scenario2 2000
CodeGen scenario3 2000
CodeGen scenario4 2000

In [77]:
project_df.to_csv('project.csv', index=False)

In [78]:
codex_test_df= pd.read_csv('/Users/lsiddiqsunny/Documents/Notre_Dame/Research/ICSE23-results/OpenAI/SF110-Results/csv-data/Test_Correctness_Codex_SF110_updated.csv')
codex_test_df.head()

,MODEL,SCENARIO,TOKEN,PROJECT_NAME,CLASS_NAME,FILE_NAME,TOTAL_TESTS,TOTAL_ABORTED,TOTAL_FAILURES,TOTAL_SKIPPED,SUCCESS_RATE,TOTAL_TIME
0,Codex,original,2000,69_lhamacaw,macaw.system,original_StartupOptions_useDemo_2000_Test,13,0,8,0,38.46153846153847%,0.435
1,Codex,original,2000,14_omjstate,uk.me.jockmacmad.jstate.state,original_EndState_getSingleton_2000_0_Test,11,0,0,0,100.0%,0.230
2,Codex,original,2000,14_omjstate,uk.me.jockmacmad.jstate.state,original_EndState_toObject_2000_1_Test,10,0,0,0,100.0%,0.031
3,Codex,original,2000,14_omjstate,uk.me.jockmacmad.jstate.state,original_StartState_toObject_2000_1_Test,10,0,0,0,100.0%,0.012
4,Codex,original,2000,60_sugar,net.sf.sugar.fspath,original_FSPathResultListImpl_each_2000_0_Test,0,0,0,0,0.0%,0.000

In [79]:
model = 'Codex'
for scenario in ["original", "scenario1", "scenario2", "scenario3", "scenario4"]:
    for token in [2000,4000]:
        codex_df = codex_test_df[(codex_test_df['SCENARIO'] == scenario) & (codex_test_df['TOKEN'] == token)]
        for index, row in codex_df.iterrows():
            file = row['FILE_NAME'].split('_')[1]
            project_df.loc[(project_df['PACKAGE'] == row['CLASS_NAME']) & (project_df['CLASS'] == file), model+'_'+scenario+'_'+str(token)] = 1

In [80]:
gpt_test_df= pd.read_csv('/Users/lsiddiqsunny/Documents/Notre_Dame/Research/ICSE23-results/GPT3.5/SF110-Results/csv-data/Test_Correctness_GPT3.5_SF110_updated.csv')
gpt_test_df.head()

,MODEL,SCENARIO,TOKEN,PROJECT_NAME,CLASS_NAME,FILE_NAME,TOTAL_TESTS,TOTAL_ABORTED,TOTAL_FAILURES,TOTAL_SKIPPED,SUCCESS_RATE,TOTAL_TIME
0,ChatGPT-3.5,original,2000,69_lhamacaw,macaw.system,original_StartupOptions_useDemo_2000_Test,9,0,0,0,100.0%,0.239
1,ChatGPT-3.5,original,2000,14_omjstate,uk.me.jockmacmad.jstate.state,original_Transition_trigger_2000_0_Test,0,0,0,0,0.0%,0.000
2,ChatGPT-3.5,original,2000,14_omjstate,uk.me.jockmacmad.jstate.state,original_EndState_getSingleton_2000_0_Test,0,0,0,0,0.0%,0.000
3,ChatGPT-3.5,original,2000,14_omjstate,uk.me.jockmacmad.jstate.state,original_EndState_toObject_2000_1_Test,0,0,0,0,0.0%,0.000
4,ChatGPT-3.5,original,2000,14_omjstate,uk.me.jockmacmad.jstate.state,original_StringMatchesGuardCondition_evaluate_...,0,0,0,0,0.0%,0.000

In [81]:
model = 'ChatGPT-3.5'
for scenario in ["original", "scenario1", "scenario2", "scenario3", "scenario4"]:
    for token in [2000]:
        gpt_df = gpt_test_df[(gpt_test_df['SCENARIO'] == scenario) & (gpt_test_df['TOKEN'] == token)]
        for index, row in gpt_df.iterrows():
            file = row['FILE_NAME'].split('_')[1]
            project_df.loc[(project_df['PACKAGE'] == row['CLASS_NAME']) & (project_df['CLASS'] == file), model+'_'+scenario+'_'+str(token)] = 1

In [82]:
codegen_test_df= pd.read_csv('/Users/lsiddiqsunny/Documents/Notre_Dame/Research/ICSE23-results/CodeGen/SF110-Results/csv-data/Test_Correctness_CodeGen_SF110_updated.csv')
codegen_test_df.head()

,MODEL,SCENARIO,TOKEN,PROJECT_NAME,CLASS_NAME,FILE_NAME,TOTAL_TESTS,TOTAL_ABORTED,TOTAL_FAILURES,TOTAL_SKIPPED,SUCCESS_RATE,TOTAL_TIME
0,CodeGen,original,2000,69_lhamacaw,macaw.system,original_StartupOptions_useDemo_2000_2_Test,0,0,0,0,0.0%,0.000
1,CodeGen,original,2000,69_lhamacaw,macaw.system,original_StartupOptions_useDemo_2000_3_Test,0,0,0,0,0.0%,0.000
2,CodeGen,original,2000,69_lhamacaw,macaw.system,original_StartupOptions_useDemo_2000_8_Test,0,0,0,0,0.0%,0.000
3,CodeGen,original,2000,69_lhamacaw,macaw.system,original_StartupOptions_useDemo_2000_9_Test,0,0,0,0,0.0%,0.000
4,CodeGen,original,2000,69_lhamacaw,macaw.system,original_StartupOptions_useDemo_2000_5_Test,1,0,0,0,100.0%,0.106

In [83]:
model = 'CodeGen'
for scenario in ["original", "scenario1", "scenario2", "scenario3", "scenario4"]:
    for token in [2000]:
        codegen_df = codegen_test_df[(codegen_test_df['SCENARIO'] == scenario) & (codegen_test_df['TOKEN'] == token)]
        for index, row in codegen_df.iterrows():
            file = row['FILE_NAME'].split('_')[1]
            project_df.loc[(project_df['PACKAGE'] == row['CLASS_NAME']) & (project_df['CLASS'] == file), model+'_'+scenario+'_'+str(token)] = 1

In [84]:
project_df.to_csv('project.csv', index=False)