In [50]:
import pandas as pd

In [51]:
df = pd.read_csv('/Users/lsiddiqsunny/Documents/Notre_Dame/Research/ICSE23-results/GPT3.5/SF110-Results/csv-data/Test_Correctness_GPT3.5_SF110.csv')
df.head()

,MODEL,PROJECT_NAME,CLASS_NAME,FILE_NAME,SCENARIO,TOKEN,TOTAL_TESTS,TOTAL_FAILURES,TOTAL_SKIPPED,TOTAL_ABORTED,TOTAL_TIME
0,GPT3.5,69_lhamacaw,macaw.system,scenario4_StartupOptions_useDemo_2000_Test.java,scenario4,2000,1,1,0,0,211
1,GPT3.5,69_lhamacaw,macaw.system,original_StartupOptions_useDemo_2000_Test.java,original,2000,9,0,0,0,239
2,GPT3.5,14_omjstate,uk.me.jockmacmad.jstate.state,scenario4_StringMatchesGuardCondition_evaluate...,scenario4,2000,1,0,0,0,173
3,GPT3.5,14_omjstate,uk.me.jockmacmad.jstate.state,original_Transition_trigger_2000_0_Test.java,original,2000,0,0,0,0,0
4,GPT3.5,14_omjstate,uk.me.jockmacmad.jstate.state,scenario1_Transition_trigger_2000_0_Test.java,scenario1,2000,0,0,0,0,0

In [52]:
# df.drop('PROJECT_NAME', inplace=True, axis=1)
# df.drop('CLASS_NAME', inplace=True, axis=1)
# df.head()

In [53]:
df['MODEL'] = 'ChatGPT-3.5'
df['TOTAL_TIME'] = df['TOTAL_TIME'].div(1000)
df.head()

,MODEL,PROJECT_NAME,CLASS_NAME,FILE_NAME,SCENARIO,TOKEN,TOTAL_TESTS,TOTAL_FAILURES,TOTAL_SKIPPED,TOTAL_ABORTED,TOTAL_TIME
0,ChatGPT-3.5,69_lhamacaw,macaw.system,scenario4_StartupOptions_useDemo_2000_Test.java,scenario4,2000,1,1,0,0,0.211
1,ChatGPT-3.5,69_lhamacaw,macaw.system,original_StartupOptions_useDemo_2000_Test.java,original,2000,9,0,0,0,0.239
2,ChatGPT-3.5,14_omjstate,uk.me.jockmacmad.jstate.state,scenario4_StringMatchesGuardCondition_evaluate...,scenario4,2000,1,0,0,0,0.173
3,ChatGPT-3.5,14_omjstate,uk.me.jockmacmad.jstate.state,original_Transition_trigger_2000_0_Test.java,original,2000,0,0,0,0,0.000
4,ChatGPT-3.5,14_omjstate,uk.me.jockmacmad.jstate.state,scenario1_Transition_trigger_2000_0_Test.java,scenario1,2000,0,0,0,0,0.000

In [54]:
def get_scenario(x):
    if "TEST-" in x:
        return x.split('-')[1]
    return x

In [55]:
def get_class(x):
    classname = x.split('.')[0]
    if "TEST-" in x:
        classname = classname.split('-')[1]
    return classname

In [56]:
def calculate_success(row):
    total_tests = row['TOTAL_TESTS']
    total_success = row['TOTAL_TESTS'] - row['TOTAL_FAILURES'] - row['TOTAL_SKIPPED'] -row ['TOTAL_ABORTED']
    if total_tests == 0:
        return "0.0%"
    return str((total_success/total_tests)*100)+"%"

In [57]:
df['SCENARIO'] =  df['SCENARIO'].apply(get_scenario)
df['FILE_NAME'] =  df['FILE_NAME'].apply(get_class)

df['SUCCESS_RATE'] = df.apply(calculate_success, axis=1)
df.head()

,MODEL,PROJECT_NAME,CLASS_NAME,FILE_NAME,SCENARIO,TOKEN,TOTAL_TESTS,TOTAL_FAILURES,TOTAL_SKIPPED,TOTAL_ABORTED,TOTAL_TIME,SUCCESS_RATE
0,ChatGPT-3.5,69_lhamacaw,macaw.system,scenario4_StartupOptions_useDemo_2000_Test,scenario4,2000,1,1,0,0,0.211,0.0%
1,ChatGPT-3.5,69_lhamacaw,macaw.system,original_StartupOptions_useDemo_2000_Test,original,2000,9,0,0,0,0.239,100.0%
2,ChatGPT-3.5,14_omjstate,uk.me.jockmacmad.jstate.state,scenario4_StringMatchesGuardCondition_evaluate...,scenario4,2000,1,0,0,0,0.173,100.0%
3,ChatGPT-3.5,14_omjstate,uk.me.jockmacmad.jstate.state,original_Transition_trigger_2000_0_Test,original,2000,0,0,0,0,0.000,0.0%
4,ChatGPT-3.5,14_omjstate,uk.me.jockmacmad.jstate.state,scenario1_Transition_trigger_2000_0_Test,scenario1,2000,0,0,0,0,0.000,0.0%

In [58]:
cols = list(df.columns.values)
cols

['MODEL',
 'PROJECT_NAME',
 'CLASS_NAME',
 'FILE_NAME',
 'SCENARIO',
 'TOKEN',
 'TOTAL_TESTS',
 'TOTAL_FAILURES',
 'TOTAL_SKIPPED',
 'TOTAL_ABORTED',
 'TOTAL_TIME',
 'SUCCESS_RATE']

In [59]:
df = df[['MODEL',
         'SCENARIO',
 'TOKEN',
 'PROJECT_NAME',
 'CLASS_NAME',
 'FILE_NAME',
 'TOTAL_TESTS',
 'TOTAL_ABORTED',
 'TOTAL_FAILURES',
 'TOTAL_SKIPPED',
        'SUCCESS_RATE',
 'TOTAL_TIME']]

In [60]:
df.sort_values(by=['SCENARIO', 'TOKEN'], inplace=True)

In [61]:
df.to_csv('/Users/lsiddiqsunny/Documents/Notre_Dame/Research/ICSE23-results/GPT3.5/SF110-Results/csv-data/Test_Correctness_GPT3.5_SF110_updated.csv', index=False)